version: '3'
services:
  mysql:
    build:
      context: ./mysql
      args:
        EVENTUATE_COMMON_VERSION: ${EVENTUATE_COMMON_VERSION?}
        EVENTUATE_SAGA_VERSION: ${EVENTUATE_SAGA_VERSION?}
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw